### ISSUE TITLE
mIRC ACM missing event format causes acm.echo to fail with error * /echo: insufficient parameters (line 62, acm.mrc)

### ISSUE THREAD

**Issue by fidsah** [fofp/cocktography#1]
When calling acm.enchode from an input event, such as below, acm.echo will fail with the following error:

* /echo: insufficient parameters (line 62, acm.mrc)

Sample input event trigger:

on 1:INPUT:*: {
  if ($left($1,2) == $chr(36) $+ $chr(36)) { 
    acm.enchode $right($1-,-2)
    halt 
  }
}

Usage: Type $$test with input event

This is corrected by adding %acm.input_format

**Comment by Tefad** [comment]
This seems like a bogus problem with a bogus solution. In short, l2mSL

**Comment by fidsah** [comment]
Resolved by #3
